### ISSUE TITLE
Two answers for question 2

### ISSUE THREAD

**Issue by khataei** [sinkhat/Quiz-project#1]
![image](https://user-images.githubusercontent.com/42156128/82965686-cfe4a380-9f96-11ea-8ca2-a2245edc4a80.png)

Hey @sinkhat,

For question number two, you can select both answers. Is it on purpose?

**Comment by sinkhat** [comment]
Hey,
 it is solved. 
Thank you

**Comment by khataei** [comment]
Thanks.
